const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('deckAPI', {
  getBounds: () => ipcRenderer.invoke('deck:getBounds'),
  getOrigin: () => ipcRenderer.invoke('deck:getOrigin'),
  dockBottom: () => ipcRenderer.invoke('deck:dockBottom'),
  setReserveSpace: (value) => ipcRenderer.invoke('deck:setReserveSpace', value),
  getReserveSpace: () => ipcRenderer.invoke('deck:getReserveSpace'),
  setAlwaysOnTop: (value) => ipcRenderer.invoke('deck:setAlwaysOnTop', value),
  setOpacity: (value) => ipcRenderer.invoke('deck:setOpacity', value),
  minimize: () => ipcRenderer.invoke('deck:minimize'),
  close: () => ipcRenderer.invoke('deck:close'),
  loadPersistentState: () => ipcRenderer.invoke('deck:loadPersistentState'),
  savePersistentState: (data) => ipcRenderer.invoke('deck:savePersistentState', data),
  getPersistentPath: () => ipcRenderer.invoke('deck:getPersistentPath'),
  importPlaylistNoKey: (playlistId) => ipcRenderer.invoke('youtube:importPlaylistNoKey', playlistId),
  setTrayTooltip: (text) => ipcRenderer.invoke('deck:setTrayTooltip', text),
  ytStatus: () => ipcRenderer.invoke('yt:status'),
  ytMyPlaylists: () => ipcRenderer.invoke('yt:myPlaylists'),
  oauthStatus: () => ipcRenderer.invoke('yt:oauthStatus'),
  oauthConfigure: (clientId, clientSecret) => ipcRenderer.invoke('yt:oauthConfigure', clientId, clientSecret),
  oauthConnect: () => ipcRenderer.invoke('yt:oauthConnect'),
  oauthDisconnect: () => ipcRenderer.invoke('yt:oauthDisconnect'),
  apiPlaylists: () => ipcRenderer.invoke('yt:apiPlaylists'),
  apiPlaylistItems: (playlistId) => ipcRenderer.invoke('yt:apiPlaylistItems', playlistId),
  openExternalVideo: (videoId) => ipcRenderer.invoke('yt:openExternal', videoId),
  ytPlay: (videoId) => ipcRenderer.invoke('yt:play', videoId),
  ytCommand: (command, value) => ipcRenderer.invoke('yt:command', command, value),
  ytStop: () => ipcRenderer.invoke('yt:stop'),
  ytSetBounds: (rect) => ipcRenderer.invoke('yt:setBounds', rect),
  onLockChanged: (callback) => ipcRenderer.on('deck-lock-changed', (_event, value) => callback(value)),
  onDisplayChanged: (callback) => ipcRenderer.on('deck-display-changed', (_event, value) => callback(value)),
  onTrayCommand: (callback) => ipcRenderer.on('deck-tray-command', (_event, value) => callback(value)),
  onYtEvent: (callback) => ipcRenderer.on('yt-view-event', (_event, value) => callback(value)),
});
